module Utils::FakeResponse

  def self.fake_submit
    %Q|<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<response>
<statusCode>200</statusCode>
<statusText>Ok</statusText>
<data>
<testId>131128_RQ_1KV</testId>
<ownerKey>4acd944ed93f456537c341ed6173656213f312cb</ownerKey>
<xmlUrl>http://www.webpagetest.org/xmlResult/131127_XB_e4ef197a13b3ebeea58b1452fbbbb3be/</xmlUrl>
<userUrl>http://www.webpagetest.org/result/131127_XB_e4ef197a13b3ebeea58b1452fbbbb3be/</userUrl>
<summaryCSV>http://www.webpagetest.org/result/131127_XB_e4ef197a13b3ebeea58b1452fbbbb3be/page_data.csv</summaryCSV>
<detailCSV>http://www.webpagetest.org/result/131127_XB_e4ef197a13b3ebeea58b1452fbbbb3be/requests.csv</detailCSV>
<jsonUrl>http://www.webpagetest.org/jsonResult.php?test=131127_XB_e4ef197a13b3ebeea58b1452fbbbb3be/</jsonUrl>
</data>
</response>|
  end

  def self.cnn_status
    %Q|<?xml version="1.0" encoding="UTF-8"?>
<response>
<statusCode>200</statusCode>
<statusText>Test Complete</statusText>
</response>|
  end

  def self.google_status
    %Q|<?xml version="1.0" encoding="UTF-8"?>
<response>
<statusCode>100</statusCode>
<statusText>Test Start</statusText>
</response>|
  end

  def self.cnn_xml
    %Q|
<?xml version="1.0" encoding="UTF-8"?>
<response>
<statusCode>200</statusCode>
<statusText>Ok</statusText>
<data>
<testId>131128_RQ_1KV</testId>
<summary>http://www.webpagetest.org/result/131128_RQ_1KV/</summary>
<testUrl>http://www.cnn.com</testUrl>
<location>Dulles_IE9</location>
<from>Dulles, VA - IE 9 - &lt;b&gt;Cable&lt;/b&gt;</from>
<connectivity>Cable</connectivity>
<bwDown>5000</bwDown>
<bwUp>1000</bwUp>
<latency>28</latency>
<plr>0</plr>
<completed>Thu, 28 Nov 2013 01:02:50 +0000</completed>
<testerDNS>192.168.101.1</testerDNS>
<runs>1</runs>
<successfulFVRuns>1</successfulFVRuns>
<successfulRVRuns>1</successfulRVRuns>
<average>
<firstView>
<URL>0</URL>
<loadTime>3654</loadTime>
<TTFB>150</TTFB>
<bytesOut>146101</bytesOut>
<bytesOutDoc>109849</bytesOutDoc>
<bytesIn>3122744</bytesIn>
<bytesInDoc>1260693</bytesInDoc>
<connections>73</connections>
<requests>240</requests>
<requestsDoc>175</requestsDoc>
<responses_200>222</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>1421</render>
<fullyLoaded>11931</fullyLoaded>
<cached>0</cached>
<docTime>3654</docTime>
<domTime>0</domTime>
<score_cache>40</score_cache>
<score_cdn>90</score_cdn>
<score_gzip>98</score_gzip>
<score_cookies>86</score_cookies>
<score_keep-alive>98</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>20</score_combine>
<score_compress>73</score_compress>
<score_etags>86</score_etags>
<gzip_total>2387223</gzip_total>
<gzip_savings>31459</gzip_savings>
<minify_total>519931</minify_total>
<minify_savings>0</minify_savings>
<image_total>678161</image_total>
<image_savings>179767</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1892</domElements>
<pageSpeedVersion>1</pageSpeedVersion>
<title>0</title>
<titleTime>256</titleTime>
<loadEventStart>3673</loadEventStart>
<loadEventEnd>3900</loadEventEnd>
<domContentLoadedEventStart>2942</domContentLoadedEventStart>
<domContentLoadedEventEnd>3032</domContentLoadedEventEnd>
<lastVisualChange>13041</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>9</browser_version>
<server_count>4</server_count>
<server_rtt>48</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>779</firstPaint>
<docCPUms>2917</docCPUms>
<fullyLoadedCPUms>9251</fullyLoadedCPUms>
<docCPUpct>79</docCPUpct>
<fullyLoadedCPUpct>66</fullyLoadedCPUpct>
<date>1385582530</date>
<SpeedIndexDT>6154</SpeedIndexDT>
<SpeedIndex>6154</SpeedIndex>
<VisuallyCompleteDT>13041</VisuallyCompleteDT>
<visualComplete>13041</visualComplete>
<renderDT>1425</renderDT>
<effectiveBps>265066</effectiveBps>
<effectiveBpsDoc>359786</effectiveBpsDoc>
<avgRun>1</avgRun>
</firstView>
<repeatView>
<URL>0</URL>
<loadTime>1991</loadTime>
<TTFB>713</TTFB>
<bytesOut>74193</bytesOut>
<bytesOutDoc>55898</bytesOutDoc>
<bytesIn>1181628</bytesIn>
<bytesInDoc>166790</bytesInDoc>
<connections>44</connections>
<requests>78</requests>
<requestsDoc>49</requestsDoc>
<responses_200>61</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>684</render>
<fullyLoaded>12222</fullyLoaded>
<cached>1</cached>
<docTime>1991</docTime>
<domTime>0</domTime>
<score_cache>20</score_cache>
<score_cdn>41</score_cdn>
<score_gzip>99</score_gzip>
<score_cookies>61</score_cookies>
<score_keep-alive>96</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>92</score_etags>
<gzip_total>1137661</gzip_total>
<gzip_savings>11167</gzip_savings>
<minify_total>26478</minify_total>
<minify_savings>0</minify_savings>
<image_total>21743</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1887</domElements>
<pageSpeedVersion>1</pageSpeedVersion>
<title>0</title>
<titleTime>15</titleTime>
<loadEventStart>2006</loadEventStart>
<loadEventEnd>2361</loadEventEnd>
<domContentLoadedEventStart>1333</domContentLoadedEventStart>
<domContentLoadedEventEnd>1421</domContentLoadedEventEnd>
<lastVisualChange>13336</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>9</browser_version>
<server_count>8</server_count>
<server_rtt>56</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>215</firstPaint>
<docCPUms>1997</docCPUms>
<fullyLoadedCPUms>9298</fullyLoadedCPUms>
<docCPUpct>100</docCPUpct>
<fullyLoadedCPUpct>65</fullyLoadedCPUpct>
<date>1385582547</date>
<SpeedIndexDT>4379</SpeedIndexDT>
<SpeedIndex>4379</SpeedIndex>
<VisuallyCompleteDT>13336</VisuallyCompleteDT>
<visualComplete>13336</visualComplete>
<renderDT>688</renderDT>
<effectiveBps>102669</effectiveBps>
<effectiveBpsDoc>130508</effectiveBpsDoc>
<avgRun>1</avgRun>
</repeatView>
</average>
<standardDeviation>
<firstView>
<URL>0</URL>
<loadTime>0</loadTime>
<TTFB>0</TTFB>
<bytesOut>0</bytesOut>
<bytesOutDoc>0</bytesOutDoc>
<bytesIn>0</bytesIn>
<bytesInDoc>0</bytesInDoc>
<connections>0</connections>
<requests>0</requests>
<requestsDoc>0</requestsDoc>
<responses_200>0</responses_200>
<responses_404>0</responses_404>
<responses_other>0</responses_other>
<result>0</result>
<render>0</render>
<fullyLoaded>0</fullyLoaded>
<cached>0</cached>
<docTime>0</docTime>
<domTime>0</domTime>
<score_cache>0</score_cache>
<score_cdn>0</score_cdn>
<score_gzip>0</score_gzip>
<score_cookies>0</score_cookies>
<score_keep-alive>0</score_keep-alive>
<score_minify>0</score_minify>
<score_combine>0</score_combine>
<score_compress>0</score_compress>
<score_etags>0</score_etags>
<gzip_total>0</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>0</optimization_checked>
<aft>0</aft>
<domElements>0</domElements>
<pageSpeedVersion>0</pageSpeedVersion>
<title>0</title>
<titleTime>0</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>0</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>0</browser_version>
<server_count>0</server_count>
<server_rtt>0</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>0</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>0</docCPUms>
<fullyLoadedCPUms>0</fullyLoadedCPUms>
<docCPUpct>0</docCPUpct>
<fullyLoadedCPUpct>0</fullyLoadedCPUpct>
<date>0</date>
<SpeedIndexDT>0</SpeedIndexDT>
<SpeedIndex>0</SpeedIndex>
<VisuallyCompleteDT>0</VisuallyCompleteDT>
<visualComplete>0</visualComplete>
<renderDT>0</renderDT>
<effectiveBps>0</effectiveBps>
<effectiveBpsDoc>0</effectiveBpsDoc>
<avgRun></avgRun>
</firstView>
<repeatView>
<URL>0</URL>
<loadTime>0</loadTime>
<TTFB>0</TTFB>
<bytesOut>0</bytesOut>
<bytesOutDoc>0</bytesOutDoc>
<bytesIn>0</bytesIn>
<bytesInDoc>0</bytesInDoc>
<connections>0</connections>
<requests>0</requests>
<requestsDoc>0</requestsDoc>
<responses_200>0</responses_200>
<responses_404>0</responses_404>
<responses_other>0</responses_other>
<result>0</result>
<render>0</render>
<fullyLoaded>0</fullyLoaded>
<cached>0</cached>
<docTime>0</docTime>
<domTime>0</domTime>
<score_cache>0</score_cache>
<score_cdn>0</score_cdn>
<score_gzip>0</score_gzip>
<score_cookies>0</score_cookies>
<score_keep-alive>0</score_keep-alive>
<score_minify>0</score_minify>
<score_combine>0</score_combine>
<score_compress>0</score_compress>
<score_etags>0</score_etags>
<gzip_total>0</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>0</optimization_checked>
<aft>0</aft>
<domElements>0</domElements>
<pageSpeedVersion>0</pageSpeedVersion>
<title>0</title>
<titleTime>0</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>0</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>0</browser_version>
<server_count>0</server_count>
<server_rtt>0</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>0</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>0</docCPUms>
<fullyLoadedCPUms>0</fullyLoadedCPUms>
<docCPUpct>0</docCPUpct>
<fullyLoadedCPUpct>0</fullyLoadedCPUpct>
<date>0</date>
<SpeedIndexDT>0</SpeedIndexDT>
<SpeedIndex>0</SpeedIndex>
<VisuallyCompleteDT>0</VisuallyCompleteDT>
<visualComplete>0</visualComplete>
<renderDT>0</renderDT>
<effectiveBps>0</effectiveBps>
<effectiveBpsDoc>0</effectiveBpsDoc>
<avgRun></avgRun>
</repeatView>
</standardDeviation>
<median>
<firstView>
<run>1</run>
<URL>http://www.cnn.com</URL>
<loadTime>3654</loadTime>
<TTFB>150</TTFB>
<bytesOut>146101</bytesOut>
<bytesOutDoc>109849</bytesOutDoc>
<bytesIn>3122744</bytesIn>
<bytesInDoc>1260693</bytesInDoc>
<connections>73</connections>
<requests>240</requests>
<requestsDoc>175</requestsDoc>
<responses_200>222</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>1421</render>
<fullyLoaded>11931</fullyLoaded>
<cached>0</cached>
<docTime>3654</docTime>
<domTime>0</domTime>
<score_cache>40</score_cache>
<score_cdn>90</score_cdn>
<score_gzip>98</score_gzip>
<score_cookies>86</score_cookies>
<score_keep-alive>98</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>20</score_combine>
<score_compress>73</score_compress>
<score_etags>86</score_etags>
<gzip_total>2387223</gzip_total>
<gzip_savings>31459</gzip_savings>
<minify_total>519931</minify_total>
<minify_savings>0</minify_savings>
<image_total>678161</image_total>
<image_savings>179767</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1892</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>CNN.com - Breaking News, U.S., World, Weather, Entertainment &amp; Video News</title>
<titleTime>256</titleTime>
<loadEventStart>3673</loadEventStart>
<loadEventEnd>3900</loadEventEnd>
<domContentLoadedEventStart>2942</domContentLoadedEventStart>
<domContentLoadedEventEnd>3032</domContentLoadedEventEnd>
<lastVisualChange>13041</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>4</server_count>
<server_rtt>48</server_rtt>
<base_page_cdn></base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>779</firstPaint>
<docCPUms>2917.219</docCPUms>
<fullyLoadedCPUms>9250.859</fullyLoadedCPUms>
<docCPUpct>79</docCPUpct>
<fullyLoadedCPUpct>66</fullyLoadedCPUpct>
<date>1385582530</date>
<SpeedIndexDT>6154</SpeedIndexDT>
<SpeedIndex>6154</SpeedIndex>
<VisuallyCompleteDT>13041</VisuallyCompleteDT>
<visualComplete>13041</visualComplete>
<renderDT>1425</renderDT>
<effectiveBps>265066</effectiveBps>
<effectiveBpsDoc>359786</effectiveBpsDoc>
<PageSpeedData>http://www.webpagetest.org/result/131128_RQ_1KV/1_pagespeed.txt</PageSpeedData>
<status>
<entry>
<time>190</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1497</time>
<message></message>
</entry>
<entry>
<time>3654</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>3656</time>
<message></message>
</entry>
</status>
</firstView>
<repeatView>
<run>1</run>
<URL>http://www.cnn.com</URL>
<loadTime>1991</loadTime>
<TTFB>713</TTFB>
<bytesOut>74193</bytesOut>
<bytesOutDoc>55898</bytesOutDoc>
<bytesIn>1181628</bytesIn>
<bytesInDoc>166790</bytesInDoc>
<connections>44</connections>
<requests>78</requests>
<requestsDoc>49</requestsDoc>
<responses_200>61</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>684</render>
<fullyLoaded>12222</fullyLoaded>
<cached>1</cached>
<docTime>1991</docTime>
<domTime>0</domTime>
<score_cache>20</score_cache>
<score_cdn>41</score_cdn>
<score_gzip>99</score_gzip>
<score_cookies>61</score_cookies>
<score_keep-alive>96</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>92</score_etags>
<gzip_total>1137661</gzip_total>
<gzip_savings>11167</gzip_savings>
<minify_total>26478</minify_total>
<minify_savings>0</minify_savings>
<image_total>21743</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1887</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>CNN.com - Breaking News, U.S., World, Weather, Entertainment &amp; Video News</title>
<titleTime>15</titleTime>
<loadEventStart>2006</loadEventStart>
<loadEventEnd>2361</loadEventEnd>
<domContentLoadedEventStart>1333</domContentLoadedEventStart>
<domContentLoadedEventEnd>1421</domContentLoadedEventEnd>
<lastVisualChange>13336</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>8</server_count>
<server_rtt>56</server_rtt>
<base_page_cdn></base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>215</firstPaint>
<docCPUms>1996.813</docCPUms>
<fullyLoadedCPUms>9297.66</fullyLoadedCPUms>
<docCPUpct>100</docCPUpct>
<fullyLoadedCPUpct>65</fullyLoadedCPUpct>
<date>1385582547</date>
<SpeedIndexDT>4379</SpeedIndexDT>
<SpeedIndex>4379</SpeedIndex>
<VisuallyCompleteDT>13336</VisuallyCompleteDT>
<visualComplete>13336</visualComplete>
<renderDT>688</renderDT>
<effectiveBps>102669</effectiveBps>
<effectiveBpsDoc>130508</effectiveBpsDoc>
<PageSpeedData>http://www.webpagetest.org/result/131128_RQ_1KV/1_Cached_pagespeed.txt</PageSpeedData>
<status>
<entry>
<time>197</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>691</time>
<message></message>
</entry>
<entry>
<time>1991</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1992</time>
<message></message>
</entry>
</status>
</repeatView>
</median>
<run>
<id>1</id>
<firstView>
<results>
<URL>http://www.cnn.com</URL>
<loadTime>3654</loadTime>
<TTFB>150</TTFB>
<bytesOut>146101</bytesOut>
<bytesOutDoc>109849</bytesOutDoc>
<bytesIn>3122744</bytesIn>
<bytesInDoc>1260693</bytesInDoc>
<connections>73</connections>
<requests>240</requests>
<requestsDoc>175</requestsDoc>
<responses_200>222</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>1421</render>
<fullyLoaded>11931</fullyLoaded>
<cached>0</cached>
<docTime>3654</docTime>
<domTime>0</domTime>
<score_cache>40</score_cache>
<score_cdn>90</score_cdn>
<score_gzip>98</score_gzip>
<score_cookies>86</score_cookies>
<score_keep-alive>98</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>20</score_combine>
<score_compress>73</score_compress>
<score_etags>86</score_etags>
<gzip_total>2387223</gzip_total>
<gzip_savings>31459</gzip_savings>
<minify_total>519931</minify_total>
<minify_savings>0</minify_savings>
<image_total>678161</image_total>
<image_savings>179767</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1892</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>CNN.com - Breaking News, U.S., World, Weather, Entertainment &amp; Video News</title>
<titleTime>256</titleTime>
<loadEventStart>3673</loadEventStart>
<loadEventEnd>3900</loadEventEnd>
<domContentLoadedEventStart>2942</domContentLoadedEventStart>
<domContentLoadedEventEnd>3032</domContentLoadedEventEnd>
<lastVisualChange>13041</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>4</server_count>
<server_rtt>48</server_rtt>
<base_page_cdn></base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>779</firstPaint>
<docCPUms>2917.219</docCPUms>
<fullyLoadedCPUms>9250.859</fullyLoadedCPUms>
<docCPUpct>79</docCPUpct>
<fullyLoadedCPUpct>66</fullyLoadedCPUpct>
<date>1385582530</date>
<SpeedIndexDT>6154</SpeedIndexDT>
<SpeedIndex>6154</SpeedIndex>
<VisuallyCompleteDT>13041</VisuallyCompleteDT>
<visualComplete>13041</visualComplete>
<renderDT>1425</renderDT>
<effectiveBps>265066</effectiveBps>
<effectiveBpsDoc>359786</effectiveBpsDoc>
</results>
<pages>
<details>http://www.webpagetest.org/result/131128_RQ_1KV/1/details/</details>
<checklist>http://www.webpagetest.org/result/131128_RQ_1KV/1/performance_optimization/</checklist>
<breakdown>http://www.webpagetest.org/result/131128_RQ_1KV/1/breakdown/</breakdown>
<domains>http://www.webpagetest.org/result/131128_RQ_1KV/1/domains/</domains>
<screenShot>http://www.webpagetest.org/result/131128_RQ_1KV/1/screen_shot/</screenShot>
</pages>
<thumbnails>
<waterfall>http://www.webpagetest.org/result/131128_RQ_1KV/1_waterfall_thumb.png</waterfall>
<checklist>http://www.webpagetest.org/result/131128_RQ_1KV/1_optimization_thumb.png</checklist>
<screenShot>http://www.webpagetest.org/result/131128_RQ_1KV/1_screen_thumb.jpg</screenShot>
</thumbnails>
<images>
<waterfall>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_waterfall.png</waterfall>
<connectionView>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_connection.png</connectionView>
<checklist>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_optimization.png</checklist>
<screenShot>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_screen.jpg</screenShot>
</images>
<rawData><headers>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_report.txt</headers>
<pageData>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_IEWPG.txt</pageData>
<requestsData>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_IEWTR.txt</requestsData>
<utilization>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_progress.csv</utilization>
<PageSpeedData>http://www.webpagetest.org/result/131128_RQ_1KV/1_pagespeed.txt</PageSpeedData>
</rawData>
<VisualProgress>
<progress>
<time>1425</time>
<VisuallyComplete>0</VisuallyComplete>
</progress>
<progress>
<time>1488</time>
<VisuallyComplete>0.01</VisuallyComplete>
</progress>
<progress>
<time>1550</time>
<VisuallyComplete>0.01</VisuallyComplete>
</progress>
<progress>
<time>1610</time>
<VisuallyComplete>0.02</VisuallyComplete>
</progress>
<progress>
<time>1818</time>
<VisuallyComplete>0.02</VisuallyComplete>
</progress>
<progress>
<time>1824</time>
<VisuallyComplete>0.03</VisuallyComplete>
</progress>
<progress>
<time>1899</time>
<VisuallyComplete>0.03</VisuallyComplete>
</progress>
<progress>
<time>1965</time>
<VisuallyComplete>0.04</VisuallyComplete>
</progress>
<progress>
<time>2020</time>
<VisuallyComplete>0.09</VisuallyComplete>
</progress>
<progress>
<time>2028</time>
<VisuallyComplete>0.09</VisuallyComplete>
</progress>
<progress>
<time>2034</time>
<VisuallyComplete>0.09</VisuallyComplete>
</progress>
<progress>
<time>2097</time>
<VisuallyComplete>0.09</VisuallyComplete>
</progress>
<progress>
<time>2301</time>
<VisuallyComplete>0.1</VisuallyComplete>
</progress>
<progress>
<time>2315</time>
<VisuallyComplete>0.1</VisuallyComplete>
</progress>
<progress>
<time>2460</time>
<VisuallyComplete>0.11</VisuallyComplete>
</progress>
<progress>
<time>2473</time>
<VisuallyComplete>0.11</VisuallyComplete>
</progress>
<progress>
<time>2539</time>
<VisuallyComplete>0.11</VisuallyComplete>
</progress>
<progress>
<time>2776</time>
<VisuallyComplete>0.12</VisuallyComplete>
</progress>
<progress>
<time>2794</time>
<VisuallyComplete>0.16</VisuallyComplete>
</progress>
<progress>
<time>3056</time>
<VisuallyComplete>0.17</VisuallyComplete>
</progress>
<progress>
<time>3130</time>
<VisuallyComplete>0.22</VisuallyComplete>
</progress>
<progress>
<time>3284</time>
<VisuallyComplete>0.22</VisuallyComplete>
</progress>
<progress>
<time>3351</time>
<VisuallyComplete>0.23</VisuallyComplete>
</progress>
<progress>
<time>3363</time>
<VisuallyComplete>0.23</VisuallyComplete>
</progress>
<progress>
<time>3377</time>
<VisuallyComplete>0.24</VisuallyComplete>
</progress>
<progress>
<time>3401</time>
<VisuallyComplete>0.25</VisuallyComplete>
</progress>
<progress>
<time>3589</time>
<VisuallyComplete>0.25</VisuallyComplete>
</progress>
<progress>
<time>3622</time>
<VisuallyComplete>0.26</VisuallyComplete>
</progress>
<progress>
<time>3922</time>
<VisuallyComplete>0.26</VisuallyComplete>
</progress>
<progress>
<time>3939</time>
<VisuallyComplete>0.27</VisuallyComplete>
</progress>
<progress>
<time>3966</time>
<VisuallyComplete>0.29</VisuallyComplete>
</progress>
<progress>
<time>3981</time>
<VisuallyComplete>0.3</VisuallyComplete>
</progress>
<progress>
<time>4098</time>
<VisuallyComplete>0.31</VisuallyComplete>
</progress>
<progress>
<time>4136</time>
<VisuallyComplete>0.36</VisuallyComplete>
</progress>
<progress>
<time>4189</time>
<VisuallyComplete>0.37</VisuallyComplete>
</progress>
<progress>
<time>4239</time>
<VisuallyComplete>0.39</VisuallyComplete>
</progress>
<progress>
<time>4277</time>
<VisuallyComplete>0.41</VisuallyComplete>
</progress>
<progress>
<time>4312</time>
<VisuallyComplete>0.43</VisuallyComplete>
</progress>
<progress>
<time>4347</time>
<VisuallyComplete>0.44</VisuallyComplete>
</progress>
<progress>
<time>4403</time>
<VisuallyComplete>0.46</VisuallyComplete>
</progress>
<progress>
<time>4572</time>
<VisuallyComplete>0.46</VisuallyComplete>
</progress>
<progress>
<time>4648</time>
<VisuallyComplete>0.48</VisuallyComplete>
</progress>
<progress>
<time>4682</time>
<VisuallyComplete>0.5</VisuallyComplete>
</progress>
<progress>
<time>4716</time>
<VisuallyComplete>0.52</VisuallyComplete>
</progress>
<progress>
<time>4750</time>
<VisuallyComplete>0.53</VisuallyComplete>
</progress>
<progress>
<time>4783</time>
<VisuallyComplete>0.55</VisuallyComplete>
</progress>
<progress>
<time>4820</time>
<VisuallyComplete>0.57</VisuallyComplete>
</progress>
<progress>
<time>4871</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>4954</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>4961</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>4998</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>5016</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>5046</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>5078</time>
<VisuallyComplete>0.62</VisuallyComplete>
</progress>
<progress>
<time>5147</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5153</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5172</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5188</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5273</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5280</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5340</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5366</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5432</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5456</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5501</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5525</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5594</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5653</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5727</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5733</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5800</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5868</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5877</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5903</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>5949</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6018</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6025</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6094</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6113</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6128</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6178</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6205</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6254</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6303</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6329</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6356</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6466</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6472</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6556</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6571</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6598</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6649</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6680</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6706</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6755</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6793</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6840</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6847</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6973</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>6980</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>7037</time>
<VisuallyComplete>0.63</VisuallyComplete>
</progress>
<progress>
<time>7081</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7179</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7207</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7213</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7244</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7260</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7275</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7333</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7341</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7427</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7477</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7527</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7716</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7730</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7776</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7827</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7856</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7954</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7968</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>7986</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8030</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8077</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8092</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8127</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8197</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8206</time>
<VisuallyComplete>0.64</VisuallyComplete>
</progress>
<progress>
<time>8350</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8362</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8371</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8406</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8440</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8475</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8526</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8575</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8641</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8651</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8666</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8683</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8754</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8769</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8825</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8890</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8899</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8940</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>8975</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9044</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9076</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9094</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9138</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9176</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9240</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9281</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9314</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9355</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9381</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9426</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9481</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9531</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9576</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9591</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9643</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9678</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9744</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9782</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9827</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9841</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9932</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>9981</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>10023</time>
<VisuallyComplete>0.65</VisuallyComplete>
</progress>
<progress>
<time>10040</time>
<VisuallyComplete>0.66</VisuallyComplete>
</progress>
<progress>
<time>10084</time>
<VisuallyComplete>0.66</VisuallyComplete>
</progress>
<progress>
<time>10096</time>
<VisuallyComplete>0.66</VisuallyComplete>
</progress>
<progress>
<time>10142</time>
<VisuallyComplete>0.74</VisuallyComplete>
</progress>
<progress>
<time>10196</time>
<VisuallyComplete>0.75</VisuallyComplete>
</progress>
<progress>
<time>10217</time>
<VisuallyComplete>0.76</VisuallyComplete>
</progress>
<progress>
<time>10236</time>
<VisuallyComplete>0.77</VisuallyComplete>
</progress>
<progress>
<time>10258</time>
<VisuallyComplete>0.78</VisuallyComplete>
</progress>
<progress>
<time>10294</time>
<VisuallyComplete>0.79</VisuallyComplete>
</progress>
<progress>
<time>10315</time>
<VisuallyComplete>0.81</VisuallyComplete>
</progress>
<progress>
<time>10336</time>
<VisuallyComplete>0.82</VisuallyComplete>
</progress>
<progress>
<time>10380</time>
<VisuallyComplete>0.83</VisuallyComplete>
</progress>
<progress>
<time>10400</time>
<VisuallyComplete>0.84</VisuallyComplete>
</progress>
<progress>
<time>10420</time>
<VisuallyComplete>0.85</VisuallyComplete>
</progress>
<progress>
<time>10439</time>
<VisuallyComplete>0.86</VisuallyComplete>
</progress>
<progress>
<time>10454</time>
<VisuallyComplete>0.87</VisuallyComplete>
</progress>
<progress>
<time>10468</time>
<VisuallyComplete>0.87</VisuallyComplete>
</progress>
<progress>
<time>10481</time>
<VisuallyComplete>0.88</VisuallyComplete>
</progress>
<progress>
<time>10494</time>
<VisuallyComplete>0.88</VisuallyComplete>
</progress>
<progress>
<time>10509</time>
<VisuallyComplete>0.89</VisuallyComplete>
</progress>
<progress>
<time>10522</time>
<VisuallyComplete>0.89</VisuallyComplete>
</progress>
<progress>
<time>10535</time>
<VisuallyComplete>0.9</VisuallyComplete>
</progress>
<progress>
<time>10547</time>
<VisuallyComplete>0.9</VisuallyComplete>
</progress>
<progress>
<time>10560</time>
<VisuallyComplete>0.91</VisuallyComplete>
</progress>
<progress>
<time>10573</time>
<VisuallyComplete>0.91</VisuallyComplete>
</progress>
<progress>
<time>10586</time>
<VisuallyComplete>0.92</VisuallyComplete>
</progress>
<progress>
<time>10599</time>
<VisuallyComplete>0.92</VisuallyComplete>
</progress>
<progress>
<time>10633</time>
<VisuallyComplete>0.93</VisuallyComplete>
</progress>
<progress>
<time>10646</time>
<VisuallyComplete>0.94</VisuallyComplete>
</progress>
<progress>
<time>10659</time>
<VisuallyComplete>0.94</VisuallyComplete>
</progress>
<progress>
<time>10672</time>
<VisuallyComplete>0.95</VisuallyComplete>
</progress>
<progress>
<time>10683</time>
<VisuallyComplete>0.95</VisuallyComplete>
</progress>
<progress>
<time>10695</time>
<VisuallyComplete>0.96</VisuallyComplete>
</progress>
<progress>
<time>10708</time>
<VisuallyComplete>0.96</VisuallyComplete>
</progress>
<progress>
<time>10725</time>
<VisuallyComplete>0.97</VisuallyComplete>
</progress>
<progress>
<time>10738</time>
<VisuallyComplete>0.97</VisuallyComplete>
</progress>
<progress>
<time>10758</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10772</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10779</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10832</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10840</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10861</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10892</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10932</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10948</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10981</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>10991</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11031</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11040</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11076</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11092</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11131</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11140</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11182</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11226</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11240</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11282</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11331</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11341</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11359</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11392</time>
<VisuallyComplete>0.98</VisuallyComplete>
</progress>
<progress>
<time>11432</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11441</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11482</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11526</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11541</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11578</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11596</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11626</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11642</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11682</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11690</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11732</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11740</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11777</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11832</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11840</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11860</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11892</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11930</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11955</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11970</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>11991</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12027</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12053</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12070</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12084</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12104</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12111</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12130</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12141</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12182</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12189</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12226</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12261</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12271</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12289</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12332</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12341</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12390</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12432</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12458</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12470</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12490</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12527</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12559</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12571</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12584</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12602</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12619</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12628</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12644</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12681</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12691</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12732</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12777</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12826</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12840</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12861</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12892</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12927</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12940</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12975</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>12991</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>13032</time>
<VisuallyComplete>0.99</VisuallyComplete>
</progress>
<progress>
<time>13041</time>
<VisuallyComplete>1</VisuallyComplete>
</progress>
</VisualProgress>
<status>
<entry>
<time>190</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1497</time>
<message></message>
</entry>
<entry>
<time>3654</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>3656</time>
<message></message>
</entry>
</status>
</firstView>
<repeatView>
<results>
<URL>http://www.cnn.com</URL>
<loadTime>1991</loadTime>
<TTFB>713</TTFB>
<bytesOut>74193</bytesOut>
<bytesOutDoc>55898</bytesOutDoc>
<bytesIn>1181628</bytesIn>
<bytesInDoc>166790</bytesInDoc>
<connections>44</connections>
<requests>78</requests>
<requestsDoc>49</requestsDoc>
<responses_200>61</responses_200>
<responses_404>0</responses_404>
<responses_other>4</responses_other>
<result>99999</result>
<render>684</render>
<fullyLoaded>12222</fullyLoaded>
<cached>1</cached>
<docTime>1991</docTime>
<domTime>0</domTime>
<score_cache>20</score_cache>
<score_cdn>41</score_cdn>
<score_gzip>99</score_gzip>
<score_cookies>61</score_cookies>
<score_keep-alive>96</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>92</score_etags>
<gzip_total>1137661</gzip_total>
<gzip_savings>11167</gzip_savings>
<minify_total>26478</minify_total>
<minify_savings>0</minify_savings>
<image_total>21743</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>1887</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>CNN.com - Breaking News, U.S., World, Weather, Entertainment &amp; Video News</title>
<titleTime>15</titleTime>
<loadEventStart>2006</loadEventStart>
<loadEventEnd>2361</loadEventEnd>
<domContentLoadedEventStart>1333</domContentLoadedEventStart>
<domContentLoadedEventEnd>1421</domContentLoadedEventEnd>
<lastVisualChange>13336</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>8</server_count>
<server_rtt>56</server_rtt>
<base_page_cdn></base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>215</firstPaint>
<docCPUms>1996.813</docCPUms>
<fullyLoadedCPUms>9297.66</fullyLoadedCPUms>
<docCPUpct>100</docCPUpct>
<fullyLoadedCPUpct>65</fullyLoadedCPUpct>
<date>1385582547</date>
<SpeedIndexDT>4379</SpeedIndexDT>
<SpeedIndex>4379</SpeedIndex>
<VisuallyCompleteDT>13336</VisuallyCompleteDT>
<visualComplete>13336</visualComplete>
<renderDT>688</renderDT>
<effectiveBps>102669</effectiveBps>
<effectiveBpsDoc>130508</effectiveBpsDoc>
</results>
<pages>
<details>http://www.webpagetest.org/result/131128_RQ_1KV/1/details/cached/</details>
<checklist>http://www.webpagetest.org/result/131128_RQ_1KV/1/performance_optimization/cached/</checklist>
<report>http://www.webpagetest.org/result/131128_RQ_1KV/1/optimization_report/cached/</report>
<breakdown>http://www.webpagetest.org/result/131128_RQ_1KV/1/breakdown/</breakdown>
<domains>http://www.webpagetest.org/result/131128_RQ_1KV/1/domains/</domains>
<screenShot>http://www.webpagetest.org/result/131128_RQ_1KV/1/screen_shot/cached/</screenShot>
</pages>
<thumbnails>
<waterfall>http://www.webpagetest.org/result/131128_RQ_1KV/1_Cached_waterfall_thumb.png</waterfall>
<checklist>http://www.webpagetest.org/result/131128_RQ_1KV/1_Cached_optimization_thumb.png</checklist>
<screenShot>http://www.webpagetest.org/result/131128_RQ_1KV/1_Cached_screen_thumb.jpg</screenShot>
</thumbnails>
<images>
<waterfall>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_waterfall.png</waterfall>
<connectionView>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_connection.png</connectionView>
<checklist>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_optimization.png</checklist>
<screenShot>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_screen.jpg</screenShot>
</images>
<rawData>
<headers>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_report.txt</headers>
<pageData>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_IEWPG.txt</pageData>
<requestsData>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_IEWTR.txt</requestsData>
<utilization>http://www.webpagetest.org/results/13/11/28/RQ/1KV/1_Cached_progress.csv</utilization>
<PageSpeedData>http://www.webpagetest.org/result/131128_RQ_1KV/1_Cached_pagespeed.txt</PageSpeedData>
</rawData>
<status>
<entry>
<time>197</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>691</time>
<message></message>
</entry>
<entry>
<time>1991</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1992</time>
<message></message>
</entry>
</status>
</repeatView>
</run>
</data>
</response>
|
  end

  def self.google_xml
    %Q|
<?xml version="1.0" encoding="UTF-8"?>
<response>
<statusCode>200</statusCode>
<statusText>Ok</statusText>
<data>
<testId>131128_66_1NM</testId>
<summary>http://www.webpagetest.org/result/131128_66_1NM/</summary>
<testUrl>http://www.google.com</testUrl>
<location>Dulles_IE9</location>
<from>Dulles, VA - IE 9 - &lt;b&gt;Cable&lt;/b&gt;</from>
<connectivity>Cable</connectivity>
<bwDown>5000</bwDown>
<bwUp>1000</bwUp>
<latency>28</latency>
<plr>0</plr>
<completed>Thu, 28 Nov 2013 01:04:43 +0000</completed>
<testerDNS>192.168.101.1</testerDNS>
<runs>1</runs>
<successfulFVRuns>1</successfulFVRuns>
<successfulRVRuns>1</successfulRVRuns>
<average>
<firstView>
<URL>0</URL>
<loadTime>1126</loadTime>
<TTFB>501</TTFB>
<bytesOut>10011</bytesOut>
<bytesOutDoc>5341</bytesOutDoc>
<bytesIn>521031</bytesIn>
<bytesInDoc>329292</bytesInDoc>
<connections>8</connections>
<requests>14</requests>
<requestsDoc>9</requestsDoc>
<responses_200>12</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>661</render>
<fullyLoaded>1777</fullyLoaded>
<cached>0</cached>
<docTime>1126</docTime>
<domTime>0</domTime>
<score_cache>100</score_cache>
<score_cdn>81</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>28</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>100</score_etags>
<gzip_total>427094</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>385658</minify_total>
<minify_savings>0</minify_savings>
<image_total>91964</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1</pageSpeedVersion>
<title>0</title>
<titleTime>680</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1926</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>9</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>733</docCPUms>
<fullyLoadedCPUms>1342</fullyLoadedCPUms>
<docCPUpct>64</docCPUpct>
<fullyLoadedCPUpct>35</fullyLoadedCPUpct>
<date>1385582667</date>
<SpeedIndex>1383</SpeedIndex>
<visualComplete>1900</visualComplete>
<SpeedIndexDT>1080</SpeedIndexDT>
<VisuallyCompleteDT>1923</VisuallyCompleteDT>
<renderDT>664</renderDT>
<effectiveBps>408331</effectiveBps>
<effectiveBpsDoc>526867</effectiveBpsDoc>
<avgRun>1</avgRun>
</firstView>
<repeatView>
<URL>0</URL>
<loadTime>1211</loadTime>
<TTFB>487</TTFB>
<bytesOut>4395</bytesOut>
<bytesOutDoc>2151</bytesOutDoc>
<bytesIn>41119</bytesIn>
<bytesInDoc>40727</bytesInDoc>
<connections>5</connections>
<requests>6</requests>
<requestsDoc>4</requestsDoc>
<responses_200>1</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>693</render>
<fullyLoaded>1379</fullyLoaded>
<cached>1</cached>
<docTime>1211</docTime>
<domTime>0</domTime>
<score_cache>-1</score_cache>
<score_cdn>-1</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>66</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>-1</score_minify>
<score_combine>100</score_combine>
<score_compress>-1</score_compress>
<score_etags>100</score_etags>
<gzip_total>39539</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1</pageSpeedVersion>
<title>0</title>
<titleTime>1088</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1332</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>9</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>889</docCPUms>
<fullyLoadedCPUms>1030</fullyLoadedCPUms>
<docCPUpct>72</docCPUpct>
<fullyLoadedCPUpct>30</fullyLoadedCPUpct>
<date>1385582673</date>
<SpeedIndex>1025</SpeedIndex>
<visualComplete>1200</visualComplete>
<SpeedIndexDT>1110</SpeedIndexDT>
<VisuallyCompleteDT>1235</VisuallyCompleteDT>
<renderDT>696</renderDT>
<effectiveBps>46097</effectiveBps>
<effectiveBpsDoc>56252</effectiveBpsDoc>
<avgRun>1</avgRun>
</repeatView>
</average>
<standardDeviation>
<firstView>
<URL>0</URL>
<loadTime>0</loadTime>
<TTFB>0</TTFB>
<bytesOut>0</bytesOut>
<bytesOutDoc>0</bytesOutDoc>
<bytesIn>0</bytesIn>
<bytesInDoc>0</bytesInDoc>
<connections>0</connections>
<requests>0</requests>
<requestsDoc>0</requestsDoc>
<responses_200>0</responses_200>
<responses_404>0</responses_404>
<responses_other>0</responses_other>
<result>0</result>
<render>0</render>
<fullyLoaded>0</fullyLoaded>
<cached>0</cached>
<docTime>0</docTime>
<domTime>0</domTime>
<score_cache>0</score_cache>
<score_cdn>0</score_cdn>
<score_gzip>0</score_gzip>
<score_cookies>0</score_cookies>
<score_keep-alive>0</score_keep-alive>
<score_minify>0</score_minify>
<score_combine>0</score_combine>
<score_compress>0</score_compress>
<score_etags>0</score_etags>
<gzip_total>0</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>0</optimization_checked>
<aft>0</aft>
<domElements>0</domElements>
<pageSpeedVersion>0</pageSpeedVersion>
<title>0</title>
<titleTime>0</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>0</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>0</browser_version>
<server_count>0</server_count>
<server_rtt>0</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>0</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>0</docCPUms>
<fullyLoadedCPUms>0</fullyLoadedCPUms>
<docCPUpct>0</docCPUpct>
<fullyLoadedCPUpct>0</fullyLoadedCPUpct>
<date>0</date>
<SpeedIndex>0</SpeedIndex>
<visualComplete>0</visualComplete>
<SpeedIndexDT>0</SpeedIndexDT>
<VisuallyCompleteDT>0</VisuallyCompleteDT>
<renderDT>0</renderDT>
<effectiveBps>0</effectiveBps>
<effectiveBpsDoc>0</effectiveBpsDoc>
<avgRun></avgRun>
</firstView>
<repeatView>
<URL>0</URL>
<loadTime>0</loadTime>
<TTFB>0</TTFB>
<bytesOut>0</bytesOut>
<bytesOutDoc>0</bytesOutDoc>
<bytesIn>0</bytesIn>
<bytesInDoc>0</bytesInDoc>
<connections>0</connections>
<requests>0</requests>
<requestsDoc>0</requestsDoc>
<responses_200>0</responses_200>
<responses_404>0</responses_404>
<responses_other>0</responses_other>
<result>0</result>
<render>0</render>
<fullyLoaded>0</fullyLoaded>
<cached>0</cached>
<docTime>0</docTime>
<domTime>0</domTime>
<score_cache>0</score_cache>
<score_cdn>0</score_cdn>
<score_gzip>0</score_gzip>
<score_cookies>0</score_cookies>
<score_keep-alive>0</score_keep-alive>
<score_minify>0</score_minify>
<score_combine>0</score_combine>
<score_compress>0</score_compress>
<score_etags>0</score_etags>
<gzip_total>0</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>0</optimization_checked>
<aft>0</aft>
<domElements>0</domElements>
<pageSpeedVersion>0</pageSpeedVersion>
<title>0</title>
<titleTime>0</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>0</lastVisualChange>
<browser_name>0</browser_name>
<browser_version>0</browser_version>
<server_count>0</server_count>
<server_rtt>0</server_rtt>
<base_page_cdn>0</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>0</fixed_viewport>
<score_progressive_jpeg>0</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>0</docCPUms>
<fullyLoadedCPUms>0</fullyLoadedCPUms>
<docCPUpct>0</docCPUpct>
<fullyLoadedCPUpct>0</fullyLoadedCPUpct>
<date>0</date>
<SpeedIndex>0</SpeedIndex>
<visualComplete>0</visualComplete>
<SpeedIndexDT>0</SpeedIndexDT>
<VisuallyCompleteDT>0</VisuallyCompleteDT>
<renderDT>0</renderDT>
<effectiveBps>0</effectiveBps>
<effectiveBpsDoc>0</effectiveBpsDoc>
<avgRun></avgRun>
</repeatView>
</standardDeviation>
<median>
<firstView>
<run>1</run>
<URL>http://www.google.com</URL>
<loadTime>1126</loadTime>
<TTFB>501</TTFB>
<bytesOut>10011</bytesOut>
<bytesOutDoc>5341</bytesOutDoc>
<bytesIn>521031</bytesIn>
<bytesInDoc>329292</bytesInDoc>
<connections>8</connections>
<requests>14</requests>
<requestsDoc>9</requestsDoc>
<responses_200>12</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>661</render>
<fullyLoaded>1777</fullyLoaded>
<cached>0</cached>
<docTime>1126</docTime>
<domTime>0</domTime>
<score_cache>100</score_cache>
<score_cdn>81</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>28</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>100</score_etags>
<gzip_total>427094</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>385658</minify_total>
<minify_savings>0</minify_savings>
<image_total>91964</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>Google</title>
<titleTime>680</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1926</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>Google</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>733.205</docCPUms>
<fullyLoadedCPUms>1341.609</fullyLoadedCPUms>
<docCPUpct>64</docCPUpct>
<fullyLoadedCPUpct>35</fullyLoadedCPUpct>
<date>1385582667</date>
<SpeedIndex>1383</SpeedIndex>
<visualComplete>1900</visualComplete>
<SpeedIndexDT>1080</SpeedIndexDT>
<VisuallyCompleteDT>1923</VisuallyCompleteDT>
<renderDT>664</renderDT>
<effectiveBps>408331</effectiveBps>
<effectiveBpsDoc>526867</effectiveBpsDoc>
<PageSpeedData>http://www.webpagetest.org/result/131128_66_1NM/1_pagespeed.txt</PageSpeedData>
<status>
<entry>
<time>538</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1114</time>
<message></message>
</entry>
<entry>
<time>1126</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1127</time>
<message></message>
</entry>
</status>
</firstView>
<repeatView>
<run>1</run>
<URL>http://www.google.com</URL>
<loadTime>1211</loadTime>
<TTFB>487</TTFB>
<bytesOut>4395</bytesOut>
<bytesOutDoc>2151</bytesOutDoc>
<bytesIn>41119</bytesIn>
<bytesInDoc>40727</bytesInDoc>
<connections>5</connections>
<requests>6</requests>
<requestsDoc>4</requestsDoc>
<responses_200>1</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>693</render>
<fullyLoaded>1379</fullyLoaded>
<cached>1</cached>
<docTime>1211</docTime>
<domTime>0</domTime>
<score_cache>-1</score_cache>
<score_cdn>-1</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>66</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>-1</score_minify>
<score_combine>100</score_combine>
<score_compress>-1</score_compress>
<score_etags>100</score_etags>
<gzip_total>39539</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>Google</title>
<titleTime>1088</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1332</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>Google</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>889.206</docCPUms>
<fullyLoadedCPUms>1029.607</fullyLoadedCPUms>
<docCPUpct>72</docCPUpct>
<fullyLoadedCPUpct>30</fullyLoadedCPUpct>
<date>1385582673</date>
<SpeedIndex>1025</SpeedIndex>
<visualComplete>1200</visualComplete>
<SpeedIndexDT>1110</SpeedIndexDT>
<VisuallyCompleteDT>1235</VisuallyCompleteDT>
<renderDT>696</renderDT>
<effectiveBps>46097</effectiveBps>
<effectiveBpsDoc>56252</effectiveBpsDoc>
<PageSpeedData>http://www.webpagetest.org/result/131128_66_1NM/1_Cached_pagespeed.txt</PageSpeedData>
<status>
<entry>
<time>525</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1201</time>
<message></message>
</entry>
<entry>
<time>1211</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1212</time>
<message></message>
</entry>
</status>
</repeatView>
</median>
<run>
<id>1</id>
<firstView>
<results>
<URL>http://www.google.com</URL>
<loadTime>1126</loadTime>
<TTFB>501</TTFB>
<bytesOut>10011</bytesOut>
<bytesOutDoc>5341</bytesOutDoc>
<bytesIn>521031</bytesIn>
<bytesInDoc>329292</bytesInDoc>
<connections>8</connections>
<requests>14</requests>
<requestsDoc>9</requestsDoc>
<responses_200>12</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>661</render>
<fullyLoaded>1777</fullyLoaded>
<cached>0</cached>
<docTime>1126</docTime>
<domTime>0</domTime>
<score_cache>100</score_cache>
<score_cdn>81</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>28</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>100</score_minify>
<score_combine>100</score_combine>
<score_compress>100</score_compress>
<score_etags>100</score_etags>
<gzip_total>427094</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>385658</minify_total>
<minify_savings>0</minify_savings>
<image_total>91964</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>Google</title>
<titleTime>680</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1926</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>Google</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>733.205</docCPUms>
<fullyLoadedCPUms>1341.609</fullyLoadedCPUms>
<docCPUpct>64</docCPUpct>
<fullyLoadedCPUpct>35</fullyLoadedCPUpct>
<date>1385582667</date>
<SpeedIndex>1383</SpeedIndex>
<visualComplete>1900</visualComplete>
<SpeedIndexDT>1080</SpeedIndexDT>
<VisuallyCompleteDT>1923</VisuallyCompleteDT>
<renderDT>664</renderDT>
<effectiveBps>408331</effectiveBps>
<effectiveBpsDoc>526867</effectiveBpsDoc>
</results>
<pages>
<details>http://www.webpagetest.org/result/131128_66_1NM/1/details/</details>
<checklist>http://www.webpagetest.org/result/131128_66_1NM/1/performance_optimization/</checklist>
<breakdown>http://www.webpagetest.org/result/131128_66_1NM/1/breakdown/</breakdown>
<domains>http://www.webpagetest.org/result/131128_66_1NM/1/domains/</domains>
<screenShot>http://www.webpagetest.org/result/131128_66_1NM/1/screen_shot/</screenShot>
</pages>
<thumbnails>
<waterfall>http://www.webpagetest.org/result/131128_66_1NM/1_waterfall_thumb.png</waterfall>
<checklist>http://www.webpagetest.org/result/131128_66_1NM/1_optimization_thumb.png</checklist>
<screenShot>http://www.webpagetest.org/result/131128_66_1NM/1_screen_thumb.jpg</screenShot>
</thumbnails>
<images>
<waterfall>http://www.webpagetest.org/results/13/11/28/66/1NM/1_waterfall.png</waterfall>
<connectionView>http://www.webpagetest.org/results/13/11/28/66/1NM/1_connection.png</connectionView>
<checklist>http://www.webpagetest.org/results/13/11/28/66/1NM/1_optimization.png</checklist>
<screenShot>http://www.webpagetest.org/results/13/11/28/66/1NM/1_screen.jpg</screenShot>
</images>
<rawData><headers>http://www.webpagetest.org/results/13/11/28/66/1NM/1_report.txt</headers>
<pageData>http://www.webpagetest.org/results/13/11/28/66/1NM/1_IEWPG.txt</pageData>
<requestsData>http://www.webpagetest.org/results/13/11/28/66/1NM/1_IEWTR.txt</requestsData>
<utilization>http://www.webpagetest.org/results/13/11/28/66/1NM/1_progress.csv</utilization>
<PageSpeedData>http://www.webpagetest.org/result/131128_66_1NM/1_pagespeed.txt</PageSpeedData>
</rawData>
<videoFrames>
<frame>
<time>0</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0000.jpg</image>
<VisuallyComplete>0</VisuallyComplete>
</frame>
<frame>
<time>700</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0007.jpg</image>
<VisuallyComplete>22</VisuallyComplete>
</frame>
<frame>
<time>800</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0008.jpg</image>
<VisuallyComplete>35</VisuallyComplete>
</frame>
<frame>
<time>1100</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0011.jpg</image>
<VisuallyComplete>45</VisuallyComplete>
</frame>
<frame>
<time>1400</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0014.jpg</image>
<VisuallyComplete>51</VisuallyComplete>
</frame>
<frame>
<time>1900</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1/frame_0019.jpg</image>
<VisuallyComplete>100</VisuallyComplete>
</frame>
</videoFrames>
<VisualProgress>
<progress>
<time>664</time>
<VisuallyComplete>0.12</VisuallyComplete>
</progress>
<progress>
<time>692</time>
<VisuallyComplete>0.23</VisuallyComplete>
</progress>
<progress>
<time>714</time>
<VisuallyComplete>0.35</VisuallyComplete>
</progress>
<progress>
<time>827</time>
<VisuallyComplete>0.4</VisuallyComplete>
</progress>
<progress>
<time>1081</time>
<VisuallyComplete>0.52</VisuallyComplete>
</progress>
<progress>
<time>1099</time>
<VisuallyComplete>0.74</VisuallyComplete>
</progress>
<progress>
<time>1136</time>
<VisuallyComplete>0.75</VisuallyComplete>
</progress>
<progress>
<time>1408</time>
<VisuallyComplete>0.86</VisuallyComplete>
</progress>
<progress>
<time>1435</time>
<VisuallyComplete>0.88</VisuallyComplete>
</progress>
<progress>
<time>1923</time>
<VisuallyComplete>1</VisuallyComplete>
</progress>
</VisualProgress>
<status>
<entry>
<time>538</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1114</time>
<message></message>
</entry>
<entry>
<time>1126</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1127</time>
<message></message>
</entry>
</status>
</firstView>
<repeatView>
<results>
<URL>http://www.google.com</URL>
<loadTime>1211</loadTime>
<TTFB>487</TTFB>
<bytesOut>4395</bytesOut>
<bytesOutDoc>2151</bytesOutDoc>
<bytesIn>41119</bytesIn>
<bytesInDoc>40727</bytesInDoc>
<connections>5</connections>
<requests>6</requests>
<requestsDoc>4</requestsDoc>
<responses_200>1</responses_200>
<responses_404>0</responses_404>
<responses_other>1</responses_other>
<result>0</result>
<render>693</render>
<fullyLoaded>1379</fullyLoaded>
<cached>1</cached>
<docTime>1211</docTime>
<domTime>0</domTime>
<score_cache>-1</score_cache>
<score_cdn>-1</score_cdn>
<score_gzip>100</score_gzip>
<score_cookies>66</score_cookies>
<score_keep-alive>100</score_keep-alive>
<score_minify>-1</score_minify>
<score_combine>100</score_combine>
<score_compress>-1</score_compress>
<score_etags>100</score_etags>
<gzip_total>39539</gzip_total>
<gzip_savings>0</gzip_savings>
<minify_total>0</minify_total>
<minify_savings>0</minify_savings>
<image_total>0</image_total>
<image_savings>0</image_savings>
<optimization_checked>1</optimization_checked>
<aft>0</aft>
<domElements>282</domElements>
<pageSpeedVersion>1.12</pageSpeedVersion>
<title>Google</title>
<titleTime>1088</titleTime>
<loadEventStart>0</loadEventStart>
<loadEventEnd>0</loadEventEnd>
<domContentLoadedEventStart>0</domContentLoadedEventStart>
<domContentLoadedEventEnd>0</domContentLoadedEventEnd>
<lastVisualChange>1332</lastVisualChange>
<browser_name>Internet Explorer</browser_name>
<browser_version>9.0.8112.16421</browser_version>
<server_count>5</server_count>
<server_rtt>32</server_rtt>
<base_page_cdn>Google</base_page_cdn>
<adult_site>0</adult_site>
<fixed_viewport>-1</fixed_viewport>
<score_progressive_jpeg>-1</score_progressive_jpeg>
<firstPaint>0</firstPaint>
<docCPUms>889.206</docCPUms>
<fullyLoadedCPUms>1029.607</fullyLoadedCPUms>
<docCPUpct>72</docCPUpct>
<fullyLoadedCPUpct>30</fullyLoadedCPUpct>
<date>1385582673</date>
<SpeedIndex>1025</SpeedIndex>
<visualComplete>1200</visualComplete>
<SpeedIndexDT>1110</SpeedIndexDT>
<VisuallyCompleteDT>1235</VisuallyCompleteDT>
<renderDT>696</renderDT>
<effectiveBps>46097</effectiveBps>
<effectiveBpsDoc>56252</effectiveBpsDoc>
</results>
<pages>
<details>http://www.webpagetest.org/result/131128_66_1NM/1/details/cached/</details>
<checklist>http://www.webpagetest.org/result/131128_66_1NM/1/performance_optimization/cached/</checklist>
<report>http://www.webpagetest.org/result/131128_66_1NM/1/optimization_report/cached/</report>
<breakdown>http://www.webpagetest.org/result/131128_66_1NM/1/breakdown/</breakdown>
<domains>http://www.webpagetest.org/result/131128_66_1NM/1/domains/</domains>
<screenShot>http://www.webpagetest.org/result/131128_66_1NM/1/screen_shot/cached/</screenShot>
</pages>
<thumbnails>
<waterfall>http://www.webpagetest.org/result/131128_66_1NM/1_Cached_waterfall_thumb.png</waterfall>
<checklist>http://www.webpagetest.org/result/131128_66_1NM/1_Cached_optimization_thumb.png</checklist>
<screenShot>http://www.webpagetest.org/result/131128_66_1NM/1_Cached_screen_thumb.jpg</screenShot>
</thumbnails>
<images>
<waterfall>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_waterfall.png</waterfall>
<connectionView>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_connection.png</connectionView>
<checklist>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_optimization.png</checklist>
<screenShot>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_screen.jpg</screenShot>
</images>
<rawData>
<headers>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_report.txt</headers>
<pageData>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_IEWPG.txt</pageData>
<requestsData>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_IEWTR.txt</requestsData>
<utilization>http://www.webpagetest.org/results/13/11/28/66/1NM/1_Cached_progress.csv</utilization>
<PageSpeedData>http://www.webpagetest.org/result/131128_66_1NM/1_Cached_pagespeed.txt</PageSpeedData>
</rawData>
<videoFrames>
<frame>
<time>0</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1_cached/frame_0000.jpg</image>
<VisuallyComplete>0</VisuallyComplete>
</frame>
<frame>
<time>700</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1_cached/frame_0007.jpg</image>
<VisuallyComplete>35</VisuallyComplete>
</frame>
<frame>
<time>1200</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1_cached/frame_0012.jpg</image>
<VisuallyComplete>100</VisuallyComplete>
</frame>
<frame>
<time>1300</time>
<image>http://www.webpagetest.org/results/13/11/28/66/1NM/video_1_cached/frame_0013.jpg</image>
<VisuallyComplete>100</VisuallyComplete>
</frame>
</videoFrames>
<status>
<entry>
<time>525</time>
<message>Browser ReadyState changed to Interactive</message>
</entry>
<entry>
<time>1201</time>
<message></message>
</entry>
<entry>
<time>1211</time>
<message>Browser ReadyState changed to Complete</message>
</entry>
<entry>
<time>1212</time>
<message></message>
</entry>
</status>
</repeatView>
</run>
</data>
</response>
|
  end
end